# Site settings
title: greyfocus.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://greyfocus.com" # the base hostname & protocol for your site

# Build settings
kramdown:
        input: GFM
permalink: /:year/:month/:title/

# Navigation
pages_list:

excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap
